# Generated by Django 3.1.1 on 2020-11-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easy_score',
            field=models.IntegerField(default=0),
        ),
    ]
