# Generated by Django 3.1.1 on 2020-11-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_user_easy_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='easy_score',
            new_name='hard_point',
        ),
        migrations.AddField(
            model_name='user',
            name='easy_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_point',
            field=models.IntegerField(default=0),
        ),
    ]
