# Generated by Django 3.1.1 on 2020-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easy_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hard_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_point',
            field=models.IntegerField(default=0),
        ),
    ]
